# Generated by Django 3.2.19 on 2023-10-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileanswer',
            name='applied_tags',
        ),
        migrations.RemoveField(
            model_name='profilequestion',
            name='opt1_tags',
        ),
        migrations.RemoveField(
            model_name='profilequestion',
            name='opt2_tags',
        ),
        migrations.RemoveField(
            model_name='profilequestion',
            name='opt3_tags',
        ),
        migrations.RemoveField(
            model_name='profilequestion',
            name='opt4_tags',
        ),
    ]
